<a href="https://colab.research.google.com/github/SbMtuGit/BicycleManagementSystemFinal/blob/master/Data_Ana_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Heading Descriptors**
**Spotify headings defs**

*What makes music danceable what audio elements make a track danceable**

**danceability**
number [float]
Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.

**valence**
number [float]
A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry)

**tempo**
number [float]
The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.

**Energy**
energy
number [float]
Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.

Example: 0.842


*** what are Realtionship between these attributes*

In [ ]:
## imports needed for data analysis on csv file
## matplotlib for plotting graphs
## seaborn for styling graphs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

**First cell **

This cell includes all the needed imports for analysing the csv data file.
Numpy is used for any numerical operations
Pandas is used for data anyaltics that are needed
matplotlab is used for plotting graphs
seaborn is used for styling the plotted graphs

NB READ https://dhruv-khurjekar.medium.com/investigating-spotifys-danceability-index-other-song-attributes-1983142f7dfd

NB SPOTIFY FOR DEVS https://developer.spotify.com/documentation/web-api/reference/get-audio-features

In [ ]:
## csv file read intp a data frame with pandas
df=pd.read_csv('/content/universal_top_spotify_songs.csv')

**Second cell**

This cell creates a Dataframe using pandas so that the csv file can read and saved within the DataFrame

In [ ]:
## print the head of the csv file
pd.set_option('display.max_columns', None)
df.head(len(df))

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,duration_ms,album_name,album_release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,2plbrEY59IikOBgBGLjaoe,Die With A Smile,"Lady Gaga, Bruno Mars",1,0,1,NaN,2024-11-10,99,False,251667,Die With A Smile,2024-08-16,0.521,0.592,6,-7.777,0,0.0304,0.3080,0.000000,0.1220,0.535,157.969,3
1,5vNRhkKd0yEAg8suGBpjeY,APT.,"ROSÉ, Bruno Mars",2,0,-1,NaN,2024-11-10,97,False,169917,APT.,2024-10-18,0.777,0.783,0,-4.477,0,0.2600,0.0283,0.000000,0.3550,0.939,149.027,4
2,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,Billie Eilish,3,0,0,NaN,2024-11-10,97,False,210373,HIT ME HARD AND SOFT,2024-05-17,0.747,0.507,2,-10.171,1,0.0358,0.2000,0.060800,0.1170,0.438,104.978,4
3,7ne4VBA60CxGM75vw0EYad,That’s So True,Gracie Abrams,4,0,8,NaN,2024-11-10,90,True,166300,The Secret of Us (Deluxe),2024-10-18,0.554,0.808,1,-4.169,1,0.0368,0.2140,0.000000,0.1590,0.372,108.548,4
4,1cOboCuWYI2osTOfolMRS6,Tu Boda,"Oscar Maydon, Fuerza Regida",5,1,-1,NaN,2024-11-10,92,True,225880,Tu Boda,2024-09-26,0.694,0.651,6,-6.968,1,0.0784,0.4960,0.000014,0.0787,0.471,112.648,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407882,0AYt6NMyyLd0rLuvr0UkMH,Slime You Out (feat. SZA),"Drake, SZA",46,4,0,AE,2023-10-18,84,True,310490,For All The Dogs,2023-10-06,0.483,0.408,5,-9.243,0,0.0502,0.5080,0.000000,0.2590,0.105,88.880,3
1407883,2Gk6fi0dqt91NKvlzGsmm7,SAY MY GRACE (feat. Travis Scott),"Offset, Travis Scott",47,3,0,AE,2023-10-18,80,True,173253,SET IT OFF,2023-10-13,0.773,0.635,10,-5.060,1,0.0452,0.0585,0.000000,0.1320,0.476,121.879,4
1407884,26b3oVLrRUaaybJulow9kz,People,Libianca,48,2,0,AE,2023-10-18,88,False,184791,People,2022-12-06,0.573,0.422,10,-7.621,0,0.0678,0.5510,0.000013,0.1020,0.693,124.357,5
1407885,5ydjxBSUIDn26MFzU3asP4,Rainy Days,V,49,1,0,AE,2023-10-18,88,False,179560,Layover,2023-08-11,0.633,0.454,9,-8.016,0,0.0875,0.7390,0.000000,0.1480,0.282,74.828,4
1407886,59NraMJsLaMCVtwXTSia8i,Prada,"cassö, RAYE, D-Block Europe",50,0,0,AE,2023-10-18,94,True,132359,Prada,2023-08-11,0.638,0.717,8,-5.804,1,0.0375,0.0010,0.000002,0.1130,0.422,141.904,4

**Third Cell**
This cell deals with printing the dataframe

In [ ]:
## missing values in each column and the amount
missing_values = df.isnull().sum()
print(missing_values)

spotify_id                0
name                     29
artists                  28
daily_rank                0
daily_movement            0
weekly_movement           0
country               19157
snapshot_date             0
popularity                0
is_explicit               0
duration_ms               0
album_name              670
album_release_date      507
danceability              0
energy                    0
key                       0
loudness                  0
mode                      0
speechiness               0
acousticness              0
instrumentalness          0
liveness                  0
valence                   0
tempo                     0
time_signature            0
dtype: int64

In [ ]:
df['release_decade'] = pd.to_datetime(df['album_release_date']).dt.year // 10 * 10

In [ ]:
df_ranked = df.sort_values(['release_decade', 'popularity'], ascending=[True, False]) \
              .groupby('release_decade') \
              .head(10)

                                    spotify_id  \
release_decade
1950.0         1155261  2uFaJJtFpPDc5Pa95XzTvg
               1177572  2uFaJJtFpPDc5Pa95XzTvg
               1158107  2uFaJJtFpPDc5Pa95XzTvg
               1158058  2uFaJJtFpPDc5Pa95XzTvg
               1176813  2uFaJJtFpPDc5Pa95XzTvg
               1157768  2uFaJJtFpPDc5Pa95XzTvg
               1176917  2uFaJJtFpPDc5Pa95XzTvg
               1157727  2uFaJJtFpPDc5Pa95XzTvg
               1177163  2uFaJJtFpPDc5Pa95XzTvg
               1157666  2uFaJJtFpPDc5Pa95XzTvg

                                                          name      artists  \
release_decade
1950.0         1155261  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1177572  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1158107  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1158058  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1176813  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1157768  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1176917  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1157727  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1177163  Let It Snow! Let It Snow! Let It Snow!  Dean Martin
               1157666  Let It Snow! Let It Snow! Let It Snow!  Dean Martin

                        daily_rank  daily_movement  weekly_movement country  \
release_decade
1950.0         1155261           8              -1                0      GB
               1177572          19              -3                3      DK
               1158107           4               0                1      LU
               1158058           5               0                0      LV
               1176813          10              -1                2      IE
               1157768          15               2                4      NL
               1176917          14              -5                6      HU
               1157727          24               0                0      NO
               1177163          10              -2                0      GB
               1157666          13               1                8      NZ

                       snapshot_date  popularity  is_explicit  duration_ms  \
release_decade
1950.0         1155261    2023-12-26          95        False       117146
               1177572    2023-12-20          95        False       117146
               1158107    2023-12-25          95        False       117146
               1158058    2023-12-25          95        False       117146
               1176813    2023-12-20          95        False       117146
               1157768    2023-12-25          95        False       117146
               1176917    2023-12-20          95        False       117146
               1157727    2023-12-25          95        False       117146
               1177163    2023-12-20          95        False       117146
               1157666    2023-12-25          95        False       117146

                              album_name album_release_date  danceability  \
release_decade
1950.0         1155261  A Winter Romance         1959-01-01         0.451
               1177572  A Winter Romance         1959-01-01         0.451
               1158107  A Winter Romance         1959-01-01         0.451
               1158058  A Winter Romance         1959-01-01         0.451
               1176813  A Winter Romance         1959-01-01         0.451
               1157768  A Winter Romance         1959-01-01         0.451
               1176917  A Winter Romance         1959-01-01         0.451
               1157727  A Winter Romance         1959-01-01         0.451
               1177163  A Winter Romance         1959-01-01         0.451
               1157666  A Winter Romance         1959-01-01         0.451

                        energy  key  loudness  mode  speechiness  \
release_decade
1950.0         1155261    0.24    1   -14.014     1       0.0351
               1177572    0.24    1   -14.014     1       0.0351
               1158107    0.24    1   -14.014     1       0.0351
               1158058    0.24    1   -14.014     1       0.0351
               1176813    0.24    1   -14.014     1       0.0351
               1157768    0.24    1   -14.014     1       0.0351
               1176917    0.24    1   -14.014     1       0.0351
               1157727    0.24    1   -14.014     1       0.0351
               1177163    0.24    1   -14.014     1       0.0351
               1157666    0.24    1   -14.014     1       0.0351

                        acousticness  instrumentalness  liveness  valence  \
release_decade
1950.0         1155261         0.912          0.000002     0.175    0.701
               1177572         0.912          0.000002     0.175    0.701
               1158107         0.912          0.000002     0.175    0.701
               1158058         0.912          0.000002     0.175    0.701
               1176813         0.912          0.000002     0.175    0.701
               1157768         0.912          0.000002     0.175    0.701
               1176917         0.912          0.000002     0.175    0.701
               1157727         0.912          0.000002     0.175    0.701
               1177163         0.912          0.000002     0.175    0.701
               1157666         0.912          0.000002     0.175    0.701

                          tempo  time_signature  release_decade
release_decade
1950.0         1155261  134.009               4          1950.0
               1177572  134.009               4          1950.0
               1158107  134.009               4          1950.0
               1158058  134.009               4          1950.0
               1176813  134.009               4          1950.0
               1157768  134.009               4          1950.0
               1176917  134.009               4          1950.0
               1157727  134.009               4          1950.0
               1177163  134.009               4          1950.0
               1157666  134.009               4          1950.0

<ipython-input-21-801edd574c42>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_ranked = df.groupby('release_decade').apply(lambda x: x.sort_values('popularity', ascending=False).head(10))

IndentationError: unexpected indent (<ipython-input-20-c404e9c74be0>, line 2)